//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/Kevin Johnson/source/repos/TSQLParser/AntlrCSharp/tsql.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="tsqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ItsqlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.tsql_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTsql_file([NotNull] tsqlParser.Tsql_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.batch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBatch([NotNull] tsqlParser.BatchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.sql_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql_clauses([NotNull] tsqlParser.Sql_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.sql_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql_clause([NotNull] tsqlParser.Sql_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.dml_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDml_clause([NotNull] tsqlParser.Dml_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.ddl_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDdl_clause([NotNull] tsqlParser.Ddl_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>block_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_statement([NotNull] tsqlParser.Block_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>break_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak_statement([NotNull] tsqlParser.Break_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>continue_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinue_statement([NotNull] tsqlParser.Continue_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>goto_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoto_statement([NotNull] tsqlParser.Goto_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>if_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] tsqlParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>return_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] tsqlParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>throw_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrow_statement([NotNull] tsqlParser.Throw_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>try_catch_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTry_catch_statement([NotNull] tsqlParser.Try_catch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>waitfor_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaitfor_statement([NotNull] tsqlParser.Waitfor_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>while_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_statement([NotNull] tsqlParser.While_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>print_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint_statement([NotNull] tsqlParser.Print_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>raiseerror_statement</c>
	/// labeled alternative in <see cref="tsqlParser.cfl_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaiseerror_statement([NotNull] tsqlParser.Raiseerror_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.another_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnother_statement([NotNull] tsqlParser.Another_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.delete_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelete_statement([NotNull] tsqlParser.Delete_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.delete_statement_from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelete_statement_from([NotNull] tsqlParser.Delete_statement_fromContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.insert_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsert_statement([NotNull] tsqlParser.Insert_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.insert_statement_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsert_statement_value([NotNull] tsqlParser.Insert_statement_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_statement([NotNull] tsqlParser.Select_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.update_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdate_statement([NotNull] tsqlParser.Update_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.where_clause_dml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_clause_dml([NotNull] tsqlParser.Where_clause_dmlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.output_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput_clause([NotNull] tsqlParser.Output_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.output_dml_list_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput_dml_list_elem([NotNull] tsqlParser.Output_dml_list_elemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.output_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput_column_name([NotNull] tsqlParser.Output_column_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.create_database"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_database([NotNull] tsqlParser.Create_databaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.create_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_index([NotNull] tsqlParser.Create_indexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.create_statistics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_statistics([NotNull] tsqlParser.Create_statisticsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.create_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table([NotNull] tsqlParser.Create_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.create_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_view([NotNull] tsqlParser.Create_viewContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.view_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitView_attribute([NotNull] tsqlParser.View_attributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.alter_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_table([NotNull] tsqlParser.Alter_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.alter_database"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlter_database([NotNull] tsqlParser.Alter_databaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.database_optionspec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatabase_optionspec([NotNull] tsqlParser.Database_optionspecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.auto_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAuto_option([NotNull] tsqlParser.Auto_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.change_tracking_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChange_tracking_option([NotNull] tsqlParser.Change_tracking_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.change_tracking_option_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChange_tracking_option_list([NotNull] tsqlParser.Change_tracking_option_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.containment_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContainment_option([NotNull] tsqlParser.Containment_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.cursor_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursor_option([NotNull] tsqlParser.Cursor_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.date_correlation_optimization_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate_correlation_optimization_option([NotNull] tsqlParser.Date_correlation_optimization_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.db_encryption_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDb_encryption_option([NotNull] tsqlParser.Db_encryption_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.db_state_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDb_state_option([NotNull] tsqlParser.Db_state_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.db_update_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDb_update_option([NotNull] tsqlParser.Db_update_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.db_user_access_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDb_user_access_option([NotNull] tsqlParser.Db_user_access_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.delayed_durability_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelayed_durability_option([NotNull] tsqlParser.Delayed_durability_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.external_access_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternal_access_option([NotNull] tsqlParser.External_access_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.mixed_page_allocation_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMixed_page_allocation_option([NotNull] tsqlParser.Mixed_page_allocation_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.parameterization_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterization_option([NotNull] tsqlParser.Parameterization_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.recovery_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecovery_option([NotNull] tsqlParser.Recovery_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.service_broker_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitService_broker_option([NotNull] tsqlParser.Service_broker_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.snapshot_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSnapshot_option([NotNull] tsqlParser.Snapshot_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.sql_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql_option([NotNull] tsqlParser.Sql_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.target_recovery_time_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTarget_recovery_time_option([NotNull] tsqlParser.Target_recovery_time_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.termination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermination([NotNull] tsqlParser.TerminationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.drop_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_index([NotNull] tsqlParser.Drop_indexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.drop_procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_procedure([NotNull] tsqlParser.Drop_procedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.drop_statistics"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_statistics([NotNull] tsqlParser.Drop_statisticsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.drop_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_table([NotNull] tsqlParser.Drop_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.drop_view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_view([NotNull] tsqlParser.Drop_viewContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.create_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_type([NotNull] tsqlParser.Create_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.drop_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop_type([NotNull] tsqlParser.Drop_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.rowset_function_limited"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRowset_function_limited([NotNull] tsqlParser.Rowset_function_limitedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.openquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpenquery([NotNull] tsqlParser.OpenqueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.opendatasource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpendatasource([NotNull] tsqlParser.OpendatasourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.declare_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare_statement([NotNull] tsqlParser.Declare_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.cursor_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursor_statement([NotNull] tsqlParser.Cursor_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.execute_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecute_statement([NotNull] tsqlParser.Execute_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.execute_statement_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecute_statement_arg([NotNull] tsqlParser.Execute_statement_argContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.execute_var_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecute_var_string([NotNull] tsqlParser.Execute_var_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.security_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecurity_statement([NotNull] tsqlParser.Security_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.grant_permission"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrant_permission([NotNull] tsqlParser.Grant_permissionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.set_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_statement([NotNull] tsqlParser.Set_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.transaction_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransaction_statement([NotNull] tsqlParser.Transaction_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.go_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGo_statement([NotNull] tsqlParser.Go_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.use_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUse_statement([NotNull] tsqlParser.Use_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.execute_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecute_clause([NotNull] tsqlParser.Execute_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.declare_local"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare_local([NotNull] tsqlParser.Declare_localContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.table_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_type_definition([NotNull] tsqlParser.Table_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.column_def_table_constraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_def_table_constraints([NotNull] tsqlParser.Column_def_table_constraintsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.column_def_table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_def_table_constraint([NotNull] tsqlParser.Column_def_table_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.column_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_definition([NotNull] tsqlParser.Column_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.column_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_constraint([NotNull] tsqlParser.Column_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_constraint([NotNull] tsqlParser.Table_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.index_options"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_options([NotNull] tsqlParser.Index_optionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.index_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_option([NotNull] tsqlParser.Index_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.declare_cursor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare_cursor([NotNull] tsqlParser.Declare_cursorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.declare_set_cursor_common"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare_set_cursor_common([NotNull] tsqlParser.Declare_set_cursor_commonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.fetch_cursor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFetch_cursor([NotNull] tsqlParser.Fetch_cursorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.set_special"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_special([NotNull] tsqlParser.Set_specialContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.constant_LOCAL_ID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_LOCAL_ID([NotNull] tsqlParser.Constant_LOCAL_IDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binary_operator_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_operator_expression([NotNull] tsqlParser.Binary_operator_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>percentile_cont_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPercentile_cont_expression([NotNull] tsqlParser.Percentile_cont_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primitive_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitive_expression([NotNull] tsqlParser.Primitive_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bracket_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_expression([NotNull] tsqlParser.Bracket_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unary_operator_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator_expression([NotNull] tsqlParser.Unary_operator_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>function_call_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_expression([NotNull] tsqlParser.Function_call_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>conversion_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversion_expression([NotNull] tsqlParser.Conversion_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>case_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_expression([NotNull] tsqlParser.Case_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>column_ref_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_ref_expression([NotNull] tsqlParser.Column_ref_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>string_agg_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_agg_expression([NotNull] tsqlParser.String_agg_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>subquery_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubquery_expression([NotNull] tsqlParser.Subquery_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>over_clause_expression</c>
	/// labeled alternative in <see cref="tsqlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOver_clause_expression([NotNull] tsqlParser.Over_clause_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_expression([NotNull] tsqlParser.Constant_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubquery([NotNull] tsqlParser.SubqueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.with_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_expression([NotNull] tsqlParser.With_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.common_table_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommon_table_expression([NotNull] tsqlParser.Common_table_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.update_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdate_elem([NotNull] tsqlParser.Update_elemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.search_condition_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearch_condition_list([NotNull] tsqlParser.Search_condition_listContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>search_cond_or</c>
	/// labeled alternative in <see cref="tsqlParser.search_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearch_cond_or([NotNull] tsqlParser.Search_cond_orContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>search_cond_pred</c>
	/// labeled alternative in <see cref="tsqlParser.search_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearch_cond_pred([NotNull] tsqlParser.Search_cond_predContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>search_cond_and</c>
	/// labeled alternative in <see cref="tsqlParser.search_condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSearch_cond_and([NotNull] tsqlParser.Search_cond_andContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unary_operator_expression3</c>
	/// labeled alternative in <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator_expression3([NotNull] tsqlParser.Unary_operator_expression3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unary_operator_expression2</c>
	/// labeled alternative in <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator_expression2([NotNull] tsqlParser.Unary_operator_expression2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binary_operator_expression2</c>
	/// labeled alternative in <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_operator_expression2([NotNull] tsqlParser.Binary_operator_expression2Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sublink_expression</c>
	/// labeled alternative in <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSublink_expression([NotNull] tsqlParser.Sublink_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binary_mod_expression</c>
	/// labeled alternative in <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_mod_expression([NotNull] tsqlParser.Binary_mod_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binary_in_expression</c>
	/// labeled alternative in <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_in_expression([NotNull] tsqlParser.Binary_in_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bracket_search_expression</c>
	/// labeled alternative in <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_search_expression([NotNull] tsqlParser.Bracket_search_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decimal_expression</c>
	/// labeled alternative in <see cref="tsqlParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimal_expression([NotNull] tsqlParser.Decimal_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bracket_query_expression</c>
	/// labeled alternative in <see cref="tsqlParser.query_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_query_expression([NotNull] tsqlParser.Bracket_query_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>query_specification_expression</c>
	/// labeled alternative in <see cref="tsqlParser.query_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_specification_expression([NotNull] tsqlParser.Query_specification_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>union_query_expression</c>
	/// labeled alternative in <see cref="tsqlParser.query_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion_query_expression([NotNull] tsqlParser.Union_query_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.union_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion_op([NotNull] tsqlParser.Union_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.query_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery_specification([NotNull] tsqlParser.Query_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.group_by_grouping_sets"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_by_grouping_sets([NotNull] tsqlParser.Group_by_grouping_setsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.grouping_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrouping_set([NotNull] tsqlParser.Grouping_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.top_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTop_clause([NotNull] tsqlParser.Top_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.top_clause_dm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTop_clause_dm([NotNull] tsqlParser.Top_clause_dmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.order_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_by_clause([NotNull] tsqlParser.Order_by_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.fetch_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFetch_expression([NotNull] tsqlParser.Fetch_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.for_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_clause([NotNull] tsqlParser.For_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.xml_common_directives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXml_common_directives([NotNull] tsqlParser.Xml_common_directivesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.order_by_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_by_expression([NotNull] tsqlParser.Order_by_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.group_by_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_by_item([NotNull] tsqlParser.Group_by_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.option_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption_clause([NotNull] tsqlParser.Option_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption([NotNull] tsqlParser.OptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.optimize_for_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptimize_for_arg([NotNull] tsqlParser.Optimize_for_argContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.select_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_list([NotNull] tsqlParser.Select_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.select_list_elem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_list_elem([NotNull] tsqlParser.Select_list_elemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.table_sources"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_sources([NotNull] tsqlParser.Table_sourcesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>cross_join</c>
	/// labeled alternative in <see cref="tsqlParser.table_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCross_join([NotNull] tsqlParser.Cross_joinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>table_source_item_join</c>
	/// labeled alternative in <see cref="tsqlParser.table_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_source_item_join([NotNull] tsqlParser.Table_source_item_joinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>standard_join</c>
	/// labeled alternative in <see cref="tsqlParser.table_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandard_join([NotNull] tsqlParser.Standard_joinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>apply_join</c>
	/// labeled alternative in <see cref="tsqlParser.table_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitApply_join([NotNull] tsqlParser.Apply_joinContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bracket_table_source</c>
	/// labeled alternative in <see cref="tsqlParser.table_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracket_table_source([NotNull] tsqlParser.Bracket_table_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>table_source_item_name</c>
	/// labeled alternative in <see cref="tsqlParser.table_source_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_source_item_name([NotNull] tsqlParser.Table_source_item_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>table_source_item_simple</c>
	/// labeled alternative in <see cref="tsqlParser.table_source_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_source_item_simple([NotNull] tsqlParser.Table_source_item_simpleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>table_source_item_complex</c>
	/// labeled alternative in <see cref="tsqlParser.table_source_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_source_item_complex([NotNull] tsqlParser.Table_source_item_complexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.tablesample_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTablesample_clause([NotNull] tsqlParser.Tablesample_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.sample_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSample_number([NotNull] tsqlParser.Sample_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.repeat_seed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeat_seed([NotNull] tsqlParser.Repeat_seedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_alias([NotNull] tsqlParser.Table_aliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.change_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChange_table([NotNull] tsqlParser.Change_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.join_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_type([NotNull] tsqlParser.Join_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.table_name_with_hint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_name_with_hint([NotNull] tsqlParser.Table_name_with_hintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.rowset_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRowset_function([NotNull] tsqlParser.Rowset_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.bulk_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBulk_option([NotNull] tsqlParser.Bulk_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.derived_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerived_table([NotNull] tsqlParser.Derived_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rank_call</c>
	/// labeled alternative in <see cref="tsqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRank_call([NotNull] tsqlParser.Rank_callContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>aggregate_call</c>
	/// labeled alternative in <see cref="tsqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregate_call([NotNull] tsqlParser.Aggregate_callContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>standard_call</c>
	/// labeled alternative in <see cref="tsqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandard_call([NotNull] tsqlParser.Standard_callContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nvf_call</c>
	/// labeled alternative in <see cref="tsqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNvf_call([NotNull] tsqlParser.Nvf_callContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>cast_call</c>
	/// labeled alternative in <see cref="tsqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCast_call([NotNull] tsqlParser.Cast_callContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>simple_call</c>
	/// labeled alternative in <see cref="tsqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_call([NotNull] tsqlParser.Simple_callContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression_call</c>
	/// labeled alternative in <see cref="tsqlParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_call([NotNull] tsqlParser.Expression_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.switch_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_section([NotNull] tsqlParser.Switch_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.switch_search_condition_section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_search_condition_section([NotNull] tsqlParser.Switch_search_condition_sectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.with_table_hints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_table_hints([NotNull] tsqlParser.With_table_hintsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.insert_with_table_hints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsert_with_table_hints([NotNull] tsqlParser.Insert_with_table_hintsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.table_hint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_hint([NotNull] tsqlParser.Table_hintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.index_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_value([NotNull] tsqlParser.Index_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.column_alias_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_alias_list([NotNull] tsqlParser.Column_alias_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_alias([NotNull] tsqlParser.Column_aliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.a_star"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitA_star([NotNull] tsqlParser.A_starContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.table_value_constructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_value_constructor([NotNull] tsqlParser.Table_value_constructorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.expression_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_list([NotNull] tsqlParser.Expression_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.value_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_list([NotNull] tsqlParser.Value_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.next_value_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNext_value_for([NotNull] tsqlParser.Next_value_forContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.next_value_for_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNext_value_for_function([NotNull] tsqlParser.Next_value_for_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.ranking_windowed_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRanking_windowed_function([NotNull] tsqlParser.Ranking_windowed_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.aggregate_windowed_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregate_windowed_function([NotNull] tsqlParser.Aggregate_windowed_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.all_distinct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAll_distinct([NotNull] tsqlParser.All_distinctContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.over_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOver_clause([NotNull] tsqlParser.Over_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.row_or_range_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRow_or_range_clause([NotNull] tsqlParser.Row_or_range_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.window_frame_extent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_frame_extent([NotNull] tsqlParser.Window_frame_extentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.window_frame_bound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_frame_bound([NotNull] tsqlParser.Window_frame_boundContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.window_frame_preceding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_frame_preceding([NotNull] tsqlParser.Window_frame_precedingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.window_frame_following"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_frame_following([NotNull] tsqlParser.Window_frame_followingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.create_database_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_database_option([NotNull] tsqlParser.Create_database_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.database_filestream_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatabase_filestream_option([NotNull] tsqlParser.Database_filestream_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.database_file_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatabase_file_spec([NotNull] tsqlParser.Database_file_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.file_group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_group([NotNull] tsqlParser.File_groupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.file_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_spec([NotNull] tsqlParser.File_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.full_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFull_table_name([NotNull] tsqlParser.Full_table_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_name([NotNull] tsqlParser.Table_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.simple_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_name([NotNull] tsqlParser.Simple_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.func_proc_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_proc_name([NotNull] tsqlParser.Func_proc_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.ddl_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDdl_object([NotNull] tsqlParser.Ddl_objectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.full_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFull_column_name([NotNull] tsqlParser.Full_column_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.column_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_name_list([NotNull] tsqlParser.Column_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.cursor_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCursor_name([NotNull] tsqlParser.Cursor_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.on_off"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOn_off([NotNull] tsqlParser.On_offContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.clustered"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClustered([NotNull] tsqlParser.ClusteredContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.null_notnull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNull_notnull([NotNull] tsqlParser.Null_notnullContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.scalar_function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalar_function_name([NotNull] tsqlParser.Scalar_function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.default_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_value([NotNull] tsqlParser.Default_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] tsqlParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSign([NotNull] tsqlParser.SignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.r_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitR_id([NotNull] tsqlParser.R_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.simple_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_id([NotNull] tsqlParser.Simple_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison_operator([NotNull] tsqlParser.Comparison_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] tsqlParser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.file_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_size([NotNull] tsqlParser.File_sizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.create_or_alter_procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_or_alter_procedure([NotNull] tsqlParser.Create_or_alter_procedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.create_or_alter_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_or_alter_function([NotNull] tsqlParser.Create_or_alter_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.func_body_returns_select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_body_returns_select([NotNull] tsqlParser.Func_body_returns_selectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.func_body_returns_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_body_returns_table([NotNull] tsqlParser.Func_body_returns_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.func_body_returns_scalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_body_returns_scalar([NotNull] tsqlParser.Func_body_returns_scalarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.procedure_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_param([NotNull] tsqlParser.Procedure_paramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.procedure_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_option([NotNull] tsqlParser.Procedure_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.function_option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_option([NotNull] tsqlParser.Function_optionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.percentile_cont"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPercentile_cont([NotNull] tsqlParser.Percentile_contContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.string_agg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_agg([NotNull] tsqlParser.String_aggContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tsqlParser.data_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitData_type([NotNull] tsqlParser.Data_typeContext context);
}
